// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cclzzjgfkmakpyrnshcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjbHp6amdma21ha3B5cm5zaGNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjMyNDAsImV4cCI6MjA2NjY5OTI0MH0.8AeXPIjm8-wruPwleAddEkvpA6xXIOGjQzqsefKzYbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);